<a href="https://colab.research.google.com/github/ShriDurga17/Machine-Learning/blob/main/AbusiveCommentDetection(Train_models).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install scikit-multilearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB 4.8 MB/s eta 0:00:00


In [ ]:
# to convert emojis to text
!pip install emot
!pip install xgboost
!pip install Textblob

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 3.8 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import nltk.data
import numpy as np
import pandas as pd
import re
import time
import string

In [ ]:
import numpy as np
import pandas as pd
import re
import gc
import os
import fileinput
import string
import tensorflow as tf
import zipfile
import datetime
import sys
from tqdm  import tqdm
tqdm.pandas()
from nltk.tokenize import wordpunct_tokenize
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score, roc_auc_score

In [ ]:
from keras.preprocessing.text import Tokenizer

from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation

from sklearn.metrics import classification_report
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
from skmultilearn.ensemble import MajorityVotingClassifier
from skmultilearn.cluster import FixedLabelSpaceClusterer
from skmultilearn.problem_transform import ClassifierChain
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.feature_extraction.text import  CountVectorizer, TfidfTransformer,TfidfVectorizer
from sklearn.ensemble import VotingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

from textblob import TextBlob

In [ ]:
import nltk.data
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.ensemble import VotingClassifier
import pandas as pd
import re
import string
from xgboost import XGBClassifier
from sklearn.feature_extraction.text import TfidfTransformer

In [ ]:
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split

#IMPORTING DATASETS


In [ ]:
df=pd.read_csv('/content/ta-misogyny-train (1).csv')

In [ ]:
df.shape

(2239, 1)

In [ ]:
dev=pd.read_csv('/content/ta-misogyny-dev.csv')

In [ ]:
dev.shape

(559, 1)

In [ ]:
dev[['Category','Cont']] = df.Content.str.split("\t",expand=True)

In [ ]:
dev=dev[['Category','Cont']]

In [ ]:
df[['Category','Cont']] = df.Content.str.split("\t",expand=True)

In [ ]:
df=df[['Category','Cont']]

In [ ]:
data=df

In [ ]:
test=pd.read_csv('/content/tamil_test_without_labels.csv')

# VALUE COUNT

In [ ]:
data = data.mask(lambda x: x['Category'] == 'Not-Tamil')
df_filtered = data.mask(lambda x: x['Category'] == 'Not-Tamil')

In [ ]:
data['Category'].value_counts()

None-of-the-above    1296
Misandry              446
Counter-speech        149
Misogyny              125
Xenophobia             95
Hope-Speech            85
Homophobia             35
Transphobic             6
Name: Category, dtype: int64

CLEAN TEXT IMPORT

In [ ]:
pip install clean-text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.4/175.4 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 5.7 MB/s eta 0:00:00
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171033 sha256=f867e2fe16b7911c35e6e48bec66ac3ff52e7a35eb56c24e1c7b26033f3bfd16
  Stored in directory: /root/.cache/pip/wheels/31/8a/8c/315c9e5d7773f74b33d5ed33f075b49c6eaeb7cedbb86e2cf8
Successfully built emoji


In [ ]:
!pip install Keras-Preprocessing
import numpy as np
import pandas as pd
import nltk
import tensorflow as tf
from nltk.corpus import stopwords
from nltk.corpus import reuters
from nltk.corpus import brown
from nltk.corpus import gutenberg
from nltk.tokenize import RegexpTokenizer
from nltk.stem import SnowballStemmer
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import pickle
import joblib
from collections import Counter
from textblob import Word
from wordcloud import WordCloud
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC, SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, AdaBoostClassifier, VotingClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, f1_score, recall_score
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential, load_model
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from keras_preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical
from keras.layers import Activation, Dense, Embedding, LSTM, SpatialDropout1D, Dropout, Flatten, GRU, Conv1D, MaxPooling1D, Bidirectional
from wordcloud import WordCloud,ImageColorGenerator
from PIL import Image
import urllib
import requests
import re
!pip install ktrain
import ktrain
from ktrain import text
sns.set()
%matplotlib inline
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('gutenberg')
nltk.download('brown')
nltk.download("reuters")
nltk.download('words')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 4.2 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.3/25.3 MB 23.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 52.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 653.6/653.6 kB 39.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 68.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 59.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.8/468.8 kB 37.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ...

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.
[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package reuters to /root/nltk_data...
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


True

In [ ]:
from cleantext import clean

# DATA CLEANING

In [ ]:
data['clean'] = df_filtered['Cont'].apply(lambda x:clean(x))
data.head()


dev['clean'] = dev['Cont'].apply(lambda x:clean(x))
dev.head()

Category                                               Cont  \
0  None-of-the-above  எச். ராசாவால் இராமருக்கே  இழிவு. இவர் எல்லாம் ...   
1  None-of-the-above  கல்யாணம்னு  வரும்போது தான் சாதி முக்கியம் எங்க...   
2  None-of-the-above                 Tentu Kottai ஐயா நான் தமிழ் இந்து.   
3         Homophobia  Tamil selvan  அடே தேவடியாவுக்கு பிரந்தவனே பச்ச...   
4  None-of-the-above  bro நீங்க பேசறதெல்லாம் கேக்க கேக்க இரவு துக்கம...   

                               clean  
0                              . . .  
1                                     
2                     tentu kottai .  
3  tamil selvan ... . tamil selva...  
4                                bro

In [ ]:
y_train=data['Category']
y_train=df_filtered['Category']
y_test=dev['Category']


y = pd.get_dummies(df_filtered['Category']).values


y_train1=pd.get_dummies(y_train).values
y_test1=pd.get_dummies(y_test).values
diz_label = {}
for i,Category in enumerate(df_filtered.Category.factorize()[1]):
    diz_label[i] = Category

diz_label

{0: 'None-of-the-above',
 1: 'Homophobia',
 2: 'Misandry',
 3: 'Counter-speech',
 4: 'Misogyny',
 5: 'Xenophobia',
 6: 'Transphobic',
 7: 'Hope-Speech'}

# DATA PREPROCESSING

In [ ]:
data_train=data

In [ ]:
count_vect = CountVectorizer()
cv_vect= count_vect.fit(data_train["Cont"])
cv_vect_train= count_vect.transform(data_train["Cont"])
cv_vect_test= count_vect.transform(dev["Cont"])


tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit(cv_vect_train)
X_tfidf_train = tfidf_transformer.transform(cv_vect_train)
X_tfidf_test = tfidf_transformer.transform(cv_vect_test)

# SMOTE

In [ ]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(sampling_strategy='minority', random_state=42)


strategy = {0:3720, 1:3720, 2:3720, 3:3720, 4:3720, 5:3720,6:3720,7:3720}
oversample = SMOTE(sampling_strategy=strategy)
X_train, y_train = oversample.fit_resample(X_tfidf_train, y_train1)

# MLP

In [ ]:
tfidf_vect_ngram_chars = TfidfVectorizer(analyzer='char', ngram_range=(2,3))
tfidf_vect_ngram_chars.fit(data['clean'])
xtrain_tfidf_ngram_chars =  tfidf_vect_ngram_chars.transform(data['clean'])
xvalid_tfidf_ngram_chars =  tfidf_vect_ngram_chars.transform(dev['clean'])



# MACHINE LEARNING

# Decicion Tree

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xtrain_tfidf_ngram_chars,y_train1, test_size=0.2, random_state=42)

In [ ]:
from sklearn import tree
modeld = tree.DecisionTreeClassifier()
modeld.fit(X_train,y_train)
y_predd=modeld.predict(X_test)

In [ ]:
print(classification_report(y_test,y_predd))
print(confusion_matrix(y_test.argmax(axis=1),y_predd.argmax(axis=1)) )
accuracy = accuracy_score(y_test,y_predd)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       0.44      0.24      0.31        29
           1       0.00      0.00      0.00         6
           2       0.00      0.00      0.00        12
           3       0.28      0.07      0.11       104
           4       0.25      0.11      0.15        27
           5       0.61      0.85      0.71       256
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00        12

   micro avg       0.56      0.52      0.54       447
   macro avg       0.20      0.16      0.16       447
weighted avg       0.46      0.52      0.46       447
 samples avg       0.52      0.52      0.52       447

[[ 10   0   0   1   1  17   0   1]
 [  1   0   0   0   0   4   0   1]
 [  0   0   0   1   0  11   0   0]
 [ 10   0   2   7   0  84   1   0]
 [  7   0   0   1   3  16   0   0]
 [ 18   0   0  13   7 217   0   1]
 [  1   0   0   0   0   0   0   0]
 [  1   0   0   2   1   8   0   0]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
modelrf = RandomForestClassifier()
modelrf.fit(X_train,y_train)
y_predrf=modelrf.predict(X_test)

print(classification_report(y_test,y_predrf))
print(confusion_matrix(y_test.argmax(axis=1),y_predrf.argmax(axis=1)) )
accuracy = accuracy_score(y_test,y_predrf)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       0.43      0.10      0.17        29
           1       0.00      0.00      0.00         6
           2       0.00      0.00      0.00        12
           3       0.43      0.03      0.05       104
           4       0.25      0.04      0.06        27
           5       0.60      0.89      0.72       256
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00        12

   micro avg       0.59      0.52      0.55       447
   macro avg       0.21      0.13      0.13       447
weighted avg       0.49      0.52      0.44       447
 samples avg       0.52      0.52      0.52       447

[[ 10   0   0   0   0  20   0   0]
 [  1   0   0   0   0   5   0   0]
 [  1   0   0   0   0  11   0   0]
 [ 11   0   2   3   2  86   0   0]
 [  9   0   0   0   1  17   0   0]
 [ 26   0   0   2   1 227   0   0]
 [  0   0   0   1   0   0   0   0]
 [  0   0   0   1   0  11   0   0]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
modelkn=KNeighborsClassifier(n_neighbors=5)
modelkn.fit(X_train,y_train)
y_predkn=modelkn.predict(X_test)


print(classification_report(y_test,y_predkn))
print(confusion_matrix(y_test.argmax(axis=1),y_predkn.argmax(axis=1)) )
accuracy = accuracy_score(y_test,y_predkn)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       0.50      0.10      0.17        29
           1       0.00      0.00      0.00         6
           2       0.00      0.00      0.00        12
           3       0.25      0.03      0.05       104
           4       1.00      0.07      0.14        27
           5       0.62      0.86      0.72       256
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00        12

   micro avg       0.61      0.51      0.55       447
   macro avg       0.30      0.13      0.14       447
weighted avg       0.51      0.51      0.44       447
 samples avg       0.51      0.51      0.51       447

[[  9   0   0   0   0  21   0   0]
 [  1   0   0   0   0   5   0   0]
 [  0   0   0   2   0  10   0   0]
 [ 26   0   0   3   0  75   0   0]
 [  9   0   0   0   2  16   0   0]
 [ 30   0   0   6   0 220   0   0]
 [  0   0   0   1   0   0   0   0]
 [  4   0   0   0   0   8   0   0]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# XG Boost

In [ ]:
from xgboost import XGBClassifier
modelxg = XGBClassifier()
modelxg.fit(X_train,y_train)
y_predxg=modelxg.predict(X_test)


print(classification_report(y_test,y_predxg))
print(confusion_matrix(y_test.argmax(axis=1),y_predxg.argmax(axis=1)) )
accuracy = accuracy_score(y_test,y_predxg)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       0.38      0.17      0.24        29
           1       0.00      0.00      0.00         6
           2       0.00      0.00      0.00        12
           3       0.50      0.07      0.12       104
           4       1.00      0.07      0.14        27
           5       0.61      0.86      0.71       256
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00        12

   micro avg       0.59      0.52      0.56       447
   macro avg       0.31      0.15      0.15       447
weighted avg       0.55      0.52      0.46       447
 samples avg       0.51      0.52      0.52       447

[[ 13   0   0   0   0  17   0   0]
 [  0   0   0   0   0   6   0   0]
 [  3   0   0   0   0   9   0   0]
 [ 14   0   2   7   0  80   0   1]
 [ 11   0   0   1   2  13   0   0]
 [ 33   0   1   4   0 217   0   1]
 [  0   0   0   1   0   0   0   0]
 [  2   0   0   1   0   9   0   0]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df["Cont"],df["Category"], test_size = 0.25, random_state = 42)
count_vect = CountVectorizer(ngram_range=(1, 2))
transformer = TfidfTransformer(norm='l2',sublinear_tf=True)
x_train_counts = count_vect.fit_transform(x_train)
x_train_tfidf = transformer.fit_transform(x_train_counts)

x_test_counts = count_vect.transform(x_test)
x_test_tfidf = transformer.transform(x_test_counts)

print (x_train_tfidf.shape,x_test_tfidf.shape, y_train.shape, y_test.shape)



(1679, 11765) (560, 11765) (1679,) (560,)


In [ ]:
joblib.dump(count_vect, 'count_vect.pkl')

['count_vect.pkl']

In [ ]:
rfc = RandomForestClassifier(n_estimators=300, max_depth=15, random_state=42, class_weight='balanced')
rfc.fit(x_train_tfidf,y_train)
y_pred4 = rfc.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_test,y_pred4)))
print(classification_report(y_test, y_pred4))
print(confusion_matrix(y_test, y_pred4))

Accuracy: 0.5732142857142857
                   precision    recall  f1-score   support

   Counter-speech       0.41      0.29      0.34        38
       Homophobia       0.28      0.62      0.38         8
      Hope-Speech       0.29      0.13      0.18        15
         Misandry       0.49      0.57      0.53       129
         Misogyny       0.32      0.29      0.30        28
None-of-the-above       0.73      0.66      0.69       323
        Not-Tamil       0.00      0.00      0.00         1
      Transphobic       0.00      0.00      0.00         1
       Xenophobia       0.22      0.47      0.30        17

         accuracy                           0.57       560
        macro avg       0.30      0.34      0.30       560
     weighted avg       0.60      0.57      0.58       560

[[ 11   0   0   2   1  20   0   0   4]
 [  0   5   0   3   0   0   0   0   0]
 [  0   0   2   0   0  13   0   0   0]
 [  1   6   0  74   8  31   0   2   7]
 [  2   2   0   4   8   9   0   2   1]
 [ 13 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
lr = LogisticRegression(C = 2, max_iter = 1000, n_jobs=-1)
lr.fit(x_train_tfidf, y_train)
y_pred1 = lr.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_test,y_pred1)))
print(classification_report(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))


Accuracy: 0.6803571428571429
                   precision    recall  f1-score   support

   Counter-speech       0.75      0.08      0.14        38
       Homophobia       1.00      0.38      0.55         8
      Hope-Speech       0.00      0.00      0.00        15
         Misandry       0.71      0.47      0.57       129
         Misogyny       0.75      0.21      0.33        28
None-of-the-above       0.68      0.95      0.79       323
        Not-Tamil       0.00      0.00      0.00         1
      Transphobic       0.00      0.00      0.00         1
       Xenophobia       0.00      0.00      0.00        17

         accuracy                           0.68       560
        macro avg       0.43      0.23      0.26       560
     weighted avg       0.66      0.68      0.62       560

[[  3   0   0   0   0  34   0   0   1]
 [  0   3   0   4   0   1   0   0   0]
 [  0   0   0   0   0  15   0   0   0]
 [  0   0   0  61   2  64   0   0   2]
 [  0   0   0   4   6  18   0   0   0]
 [  1 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svc = LinearSVC()
svc.fit(x_train_tfidf, y_train)
y_pred2 = svc.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_test,y_pred2)))
print(classification_report(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))

Accuracy: 0.6696428571428571
                   precision    recall  f1-score   support

   Counter-speech       0.26      0.16      0.20        38
       Homophobia       0.50      0.62      0.56         8
      Hope-Speech       0.40      0.13      0.20        15
         Misandry       0.68      0.51      0.58       129
         Misogyny       0.53      0.32      0.40        28
None-of-the-above       0.72      0.89      0.79       323
        Not-Tamil       0.00      0.00      0.00         1
      Transphobic       0.00      0.00      0.00         1
       Xenophobia       0.11      0.06      0.08        17

         accuracy                           0.67       560
        macro avg       0.36      0.30      0.31       560
     weighted avg       0.64      0.67      0.64       560

[[  6   0   0   0   0  31   0   0   1]
 [  0   5   0   3   0   0   0   0   0]
 [  0   0   2   0   0  13   0   0   0]
 [  3   2   1  66   7  46   0   0   4]
 [  2   1   0   5   9  11   0   0   0]
 [ 12 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:

mnb = MultinomialNB()
mnb.fit(x_train_tfidf, y_train)
y_pred3 = mnb.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_test,y_pred3)))
print(classification_report(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))

Accuracy: 0.5964285714285714
                   precision    recall  f1-score   support

   Counter-speech       0.00      0.00      0.00        38
       Homophobia       0.00      0.00      0.00         8
      Hope-Speech       0.00      0.00      0.00        15
         Misandry       0.81      0.10      0.18       129
         Misogyny       0.00      0.00      0.00        28
None-of-the-above       0.59      0.99      0.74       323
        Not-Tamil       0.00      0.00      0.00         1
      Transphobic       0.00      0.00      0.00         1
       Xenophobia       0.00      0.00      0.00        17

         accuracy                           0.60       560
        macro avg       0.16      0.12      0.10       560
     weighted avg       0.53      0.60      0.47       560

[[  0   0   0   0   0  38   0   0   0]
 [  0   0   0   0   0   8   0   0   0]
 [  0   0   0   0   0  15   0   0   0]
 [  0   0   0  13   0 116   0   0   0]
 [  0   0   0   1   0  27   0   0   0]
 [  0 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
gbc = GradientBoostingClassifier(n_estimators=100, max_features='auto', max_depth=4, random_state=1, verbose=1)
gbc.fit(x_train_tfidf, y_train)
y_pred5 = gbc.predict(x_test_tfidf)
print(accuracy_score(y_test, y_pred5))
print(classification_report(y_test, y_pred5))
print(confusion_matrix(y_test, y_pred5))

      Iter       Train Loss   Remaining Time 
         1           1.1470            1.03m
         2           1.0787            1.08m
         3           1.0258            1.09m
         4           0.9823            1.09m
         5           0.9473            1.06m
         6           0.9177            1.05m
         7           0.8856            1.03m
         8           0.8577           58.94s
         9           0.8332           55.47s
        10           0.8058           52.62s
        20           0.6360           38.27s
        30           0.5628           28.26s
        40           0.5131           21.08s
        50           0.4718           16.46s
        60           0.4359           12.97s
        70           0.4084            9.23s
        80           0.3842            5.86s
        90           0.3627            2.82s
       100           0.3438            0.00s
0.6803571428571429
                   precision    recall  f1-score   support

   Counter-speech   

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
mnb = MultinomialNB()
rfc= RandomForestClassifier(n_estimators=1000, max_depth=12, random_state=42)
lr = LogisticRegression(C = 2, max_iter = 1000, n_jobs=-1)
svc = SVC(probability=True)
ec=VotingClassifier(estimators=[('Multinominal NB', mnb), ('Random Forest', rfc),('Logistic Regression',lr),('Support Vector Machine',svc)], voting='soft', weights=[1,2,3,4])
ec.fit(x_train_tfidf,y_train)
y_pred6 = ec.predict(x_test_tfidf)
print(accuracy_score(y_test, y_pred6))
print(classification_report(y_test, y_pred6))

0.6875
                   precision    recall  f1-score   support

   Counter-speech       0.56      0.13      0.21        38
       Homophobia       0.57      0.50      0.53         8
      Hope-Speech       0.00      0.00      0.00        15
         Misandry       0.77      0.47      0.59       129
         Misogyny       0.58      0.25      0.35        28
None-of-the-above       0.69      0.94      0.80       323
        Not-Tamil       0.00      0.00      0.00         1
      Transphobic       0.00      0.00      0.00         1
       Xenophobia       0.27      0.18      0.21        17

         accuracy                           0.69       560
        macro avg       0.38      0.28      0.30       560
     weighted avg       0.66      0.69      0.64       560



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
rfc = RandomForestClassifier(n_estimators=100, max_depth=9, random_state=0)
abc= AdaBoostClassifier(base_estimator=rfc, learning_rate=0.2, n_estimators=100)
abc.fit(x_train_tfidf, y_train)
y_pred7= abc.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_test, y_pred7)))
print(classification_report(y_test, y_pred7))
print(confusion_matrix(y_test, y_pred7))

Accuracy: 0.6428571428571429
                   precision    recall  f1-score   support

   Counter-speech       1.00      0.03      0.05        38
       Homophobia       0.00      0.00      0.00         8
      Hope-Speech       0.00      0.00      0.00        15
         Misandry       0.74      0.30      0.43       129
         Misogyny       0.75      0.11      0.19        28
None-of-the-above       0.63      0.98      0.77       323
        Not-Tamil       0.00      0.00      0.00         1
      Transphobic       0.00      0.00      0.00         1
       Xenophobia       0.00      0.00      0.00        17

         accuracy                           0.64       560
        macro avg       0.35      0.16      0.16       560
     weighted avg       0.64      0.64      0.55       560

[[  1   0   0   0   0  37   0   0   0]
 [  0   0   0   4   1   3   0   0   0]
 [  0   0   0   0   0  15   0   0   0]
 [  0   0   0  39   0  90   0   0   0]
 [  0   0   0   3   3  22   0   0   0]
 [  0 

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
Comparison_unibi = pd.DataFrame({'Logistic Regression': [accuracy_score(y_test,y_pred1)*100,f1_score(y_test,y_pred1,average='macro')*100,recall_score(y_test, y_pred1,average='micro')*100,precision_score(y_test, y_pred1,average='micro')*100],
                            'SVM':[accuracy_score(y_test,y_pred2)*100,f1_score(y_test,y_pred2,average='macro')*100,recall_score(y_test, y_pred2,average='micro')*100,precision_score(y_test, y_pred2,average='micro')*100],
                           'Naive Bayes':[accuracy_score(y_test,y_pred3)*100,f1_score(y_test,y_pred3,average='macro')*100,recall_score(y_test, y_pred3,average='micro')*100,precision_score(y_test, y_pred3,average='micro')*100],
                           'Random Forest':[accuracy_score(y_test,y_pred4)*100,f1_score(y_test,y_pred4,average='macro')*100,recall_score(y_test, y_pred4,average='micro')*100,precision_score(y_test, y_pred4,average='micro')*100],
                           'GradientBoosting':[accuracy_score(y_test,y_pred5)*100,f1_score(y_test,y_pred5,average='macro')*100,recall_score(y_test, y_pred5,average='micro')*100,precision_score(y_test, y_pred5,average='micro')*100],
                           'Ensembled':[accuracy_score(y_test,y_pred6)*100,f1_score(y_test,y_pred6,average='macro')*100,recall_score(y_test, y_pred6,average='micro')*100,precision_score(y_test, y_pred6,average='micro')*100],
                           'Adaboost':[accuracy_score(y_test,y_pred7)*100,f1_score(y_test,y_pred7,average='macro')*100,recall_score(y_test, y_pred7,average='micro')*100,precision_score(y_test, y_pred7,average='micro')*100],

})

In [ ]:

print ('Comparison using uni-bi-gram(1,2)')
Comparison_unibi.rename(index={0:'Accuracy',1:'F1_score', 2: 'Recall',3:'Precision'}, inplace=True)
Comparison_unibi.head()

Comparison using uni-bi-gram(1,2)


Logistic Regression        SVM  Naive Bayes  Random Forest  \
Accuracy             68.035714  66.964286    59.642857      57.321429   
F1_score             26.465330  31.172383    10.219942      30.324113   
Recall               68.035714  66.964286    59.642857      57.321429   
Precision            68.035714  66.964286    59.642857      57.321429   

           GradientBoosting  Ensembled   Adaboost  
Accuracy          68.035714  68.750000  64.285714  
F1_score          34.091649  29.936768  15.953759  
Recall            68.035714  68.750000  64.285714  
Precision         68.035714  68.750000  64.285714

# Transfer Learning

# Bert Model

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df['Cont'], df['Category'], test_size=0.33, random_state=42)


In [ ]:

X_train = X_train.tolist()
X_test = X_test.tolist()
y_train = y_train.tolist()
y_test = y_test.tolist()

In [ ]:
class_names = ['None-of-the-above','Homophobia','Misandry','Counter-speech','Misogyny','Xenophobia','Transphobic','Hope-Speech','Not-Tamil']

In [ ]:
(x_train,y_train), (x_val,y_val), preproc = text.texts_from_array(x_train=X_train, y_train=y_train,
                                                                       x_test=X_test, y_test=y_test,
                                                                       class_names=class_names,
                                                                       preprocess_mode='bert',
                                                                       maxlen=512,
                                                                       max_features=20000)


preprocessing train...
language: ta


Is Multi-Label? False
preprocessing test...
language: ta


/usr/local/lib/python3.10/dist-packages/ktrain/utils.py:744: UserWarning: class_names argument was ignored, as they were extracted from string labels in dataset
  warnings.warn(


task: text classification


In [ ]:
model = text.text_classifier('bert', train_data=(x_train,y_train), preproc=preproc)


Is Multi-Label? False
maxlen is 512


/usr/local/lib/python3.10/dist-packages/keras/initializers/initializers.py:120: UserWarning: The initializer GlorotNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(


done.


In [ ]:
learner = ktrain.get_learner(model, train_data=(x_train,y_train),
                             val_data=(x_val,y_val),
                             batch_size=3)


In [ ]:
learner.fit_onecycle(2e-5, 3)



begin training using onecycle policy with max lr of 2e-05...
Epoch 1/3
  3/500 [..............................] - ETA: 3:24:53 - loss: 2.5687 - accuracy: 0.0000e+00

In [ ]:
learner.validate(val_data=(x_val,y_val), class_names=class_names)


24/24 [==============================] - 34s 1s/step
                   precision    recall  f1-score   support

None-of-the-above       0.33      0.04      0.07        54
       Homophobia       0.00      0.00      0.00         8
         Misandry       0.00      0.00      0.00        27
   Counter-speech       0.54      0.62      0.58       156
         Misogyny       0.70      0.18      0.29        39
       Xenophobia       0.71      0.88      0.79       431
      Transphobic       0.00      0.00      0.00         1
      Hope-Speech       0.00      0.00      0.00         1
        Not-Tamil       0.00      0.00      0.00        22

         accuracy                           0.66       739
        macro avg       0.25      0.19      0.19       739
     weighted avg       0.59      0.66      0.60       739



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


array([[  2,   0,   0,   4,   1,  47,   0,   0,   0],
       [  0,   0,   0,   8,   0,   0,   0,   0,   0],
       [  0,   0,   0,   3,   0,  24,   0,   0,   0],
       [  1,   1,   0,  97,   0,  57,   0,   0,   0],
       [  2,   2,   0,  12,   7,  16,   0,   0,   0],
       [  1,   2,   0,  45,   2, 381,   0,   0,   0],
       [  0,   0,   0,   1,   0,   0,   0,   0,   0],
       [  0,   1,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  10,   0,  12,   0,   0,   0]])

# Deep Learning

In [ ]:
vocabulary_size = 15000
max_text_len = 768
stemmer = SnowballStemmer('english')
stop_words = [word for word in stopwords.words('english') if word not in ["my","haven't","aren't","can","no", "why", "through", "herself", "she", "he", "himself", "you", "you're", "myself", "not", "here", "some", "do", "does", "did", "will", "don't", "doesn't", "didn't", "won't", "should", "should've", "couldn't", "mightn't", "mustn't", "shouldn't", "hadn't", "wasn't", "wouldn't"]]



In [ ]:
def preprocess_text(text):

    text = re.sub('[^a-zA-Z]', ' ', text)

    words = text.lower().split()

    words = [stemmer.stem(word) for word in words if not word in stop_words]

    cleaned_text = ' '.join(words)
    return cleaned_text

df['cleaned_text'] = df['Cont'].apply(preprocess_text)

In [ ]:

tokenizer = Tokenizer(num_words=vocabulary_size)
tokenizer.fit_on_texts(df['cleaned_text'].values)
le = len(tokenizer.word_index) + 1
print(le)
sequences = tokenizer.texts_to_sequences(df['cleaned_text'].values)
X_DeepLearning = pad_sequences(sequences, maxlen=max_text_len)

639


In [ ]:
df.loc[df['Category'] == 'Counter-speech' , 'LABEL'] = 0
df.loc[df['Category'] == 'Homophobia', 'LABEL'] = 1
df.loc[df['Category'] == 'Hope-Speech' , 'LABEL'] = 2
df.loc[df['Category'] == 'Misandry', 'LABEL'] = 3
df.loc[df['Category'] == 'Misogyny', 'LABEL'] = 4
df.loc[df['Category'] == 'None-of-the-above', 'LABEL'] = 5
df.loc[df['Category'] == 'Transphobic', 'LABEL'] = 6
df.loc[df['Category'] == 'Xenophobia', 'LABEL'] = 7
df.loc[df['Category'] == 'Not-Tamil', 'LABEL'] = 8

labels = to_categorical(df['LABEL'], num_classes=9)
XX_train, XX_test, y_train, y_test = train_test_split(X_DeepLearning , labels, test_size=0.25, random_state=42)
print((XX_train.shape, y_train.shape, XX_test.shape, y_test.shape))


((1679, 768), (1679, 9), (560, 768), (560, 9))


In [ ]:
epochs = 25
emb_dim = 256
batch_size = 50
model_lstm1 = Sequential()
model_lstm1.add(Embedding(vocabulary_size,emb_dim, input_length=X_DeepLearning.shape[1]))
model_lstm1.add(SpatialDropout1D(0.8))
model_lstm1.add(Bidirectional(LSTM(300, dropout=0.5, recurrent_dropout=0.5)))
model_lstm1.add(Dropout(0.5))
model_lstm1.add(Flatten())
model_lstm1.add(Dense(64, activation='relu'))
model_lstm1.add(Dropout(0.5))
model_lstm1.add(Dense(9, activation='softmax'))
model_lstm1.compile(optimizer=tf.optimizers.Adam(),loss='categorical_crossentropy', metrics=['acc'])
print(model_lstm1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 768, 256)          3840000   
                                                                 
 spatial_dropout1d_1 (Spatia  (None, 768, 256)         0         
 lDropout1D)                                                     
                                                                 
 bidirectional_1 (Bidirectio  (None, 600)              1336800   
 nal)                                                            
                                                                 
 dropout_2 (Dropout)         (None, 600)               0         
                                                                 
 flatten_1 (Flatten)         (None, 600)               0         
                                                                 
 dense_2 (Dense)             (None, 64)               

In [ ]:
checkpoint_callback = ModelCheckpoint(filepath="lastm-1-layer-best_model.h5", save_best_only=True, monitor="val_acc", mode="max", verbose=1)

early_stopping_callback = EarlyStopping(monitor="val_acc", mode="max", patience=10, verbose=1, restore_best_weights=True)

reduce_lr_callback = ReduceLROnPlateau(monitor="val_loss", factor=0.1, patience=5, verbose=1, mode="min", min_delta=0.0001, cooldown=0, min_lr=0)

callbacks=[checkpoint_callback, early_stopping_callback, reduce_lr_callback]


In [ ]:
history_lstm1 = model_lstm1.fit(XX_train, y_train, epochs = epochs, batch_size = batch_size, validation_data=(XX_test,y_test), callbacks=callbacks)


# CNN

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df['Cont'], df['Category'], test_size=0.33, random_state=42)

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y_test = le.fit_transform(y_test)
y_train=le.fit_transform(y_train)

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
vocabulary_size = 25000
tokenizer = Tokenizer(num_words= vocabulary_size)
tokenizer.fit_on_texts(X_train)
sequences = tokenizer.texts_to_sequences(X_train)
X_train1 = pad_sequences(sequences, maxlen=500)
sequences = tokenizer.texts_to_sequences(X_test)
X_test1 = pad_sequences(sequences, maxlen=500)




In [ ]:
from tensorflow.keras.layers import Embedding


In [ ]:
model = Sequential()
model.add(Embedding(20000, 1000, input_length=500))
model.add(Dropout(0.2))
model.add(Conv1D(64, 2, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(100))
model.add(Dense(8, activation='softmax'))

In [ ]:
from sklearn.utils import class_weight

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(X_train1, y_train1,batch_size=254,epochs=20,verbose=1,validation_split=0.1,)



Epoch 1/20
6/6 [==============================] - 41s 6s/step - loss: 1.8265 - accuracy: 0.5481 - val_loss: 1.3926 - val_accuracy: 0.5867
Epoch 2/20
6/6 [==============================] - 37s 6s/step - loss: 1.3815 - accuracy: 0.5948 - val_loss: 1.3526 - val_accuracy: 0.5867
Epoch 3/20
6/6 [==============================] - 42s 7s/step - loss: 1.2988 - accuracy: 0.5948 - val_loss: 1.3342 - val_accuracy: 0.5867
Epoch 4/20
6/6 [==============================] - 36s 6s/step - loss: 1.2704 - accuracy: 0.5948 - val_loss: 1.3290 - val_accuracy: 0.5867
Epoch 5/20
6/6 [==============================] - 39s 6s/step - loss: 1.2316 - accuracy: 0.5948 - val_loss: 1.3235 - val_accuracy: 0.5867
Epoch 6/20
6/6 [==============================] - 37s 6s/step - loss: 1.1766 - accuracy: 0.6156 - val_loss: 1.3325 - val_accuracy: 0.5867
Epoch 7/20
6/6 [==============================] - 38s 6s/step - loss: 1.0659 - accuracy: 0.6526 - val_loss: 1.3500 - val_accuracy: 0.5733
Epoch 8/20
6/6 [==================

In [ ]:
preds = model.predict(X_test1)

24/24 [==============================] - 4s 169ms/step


In [ ]:

pred=np.argmax(preds,axis=1)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        54
           1       0.00      0.00      0.00         8
           2       0.00      0.00      0.00        27
           3       0.27      0.23      0.25       156
           4       0.07      0.03      0.04        39
           5       0.61      0.77      0.68       431
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00        22

    accuracy                           0.50       739
   macro avg       0.11      0.11      0.11       739
weighted avg       0.41      0.50      0.45       739



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
pred=np.argmax(preds,axis=1)
print(confusion_matrix(y_test,pred))

[[  0   0   0  14   2  38   0   0   0]
 [  1   0   0   4   0   3   0   0   0]
 [  1   0   0   2   0  24   0   0   0]
 [  6   0   1  36   3 105   0   5   0]
 [  1   0   1   9   1  26   0   1   0]
 [ 10   0   5  63   8 331   0  14   0]
 [  0   0   0   0   0   1   0   0   0]
 [  0   0   0   0   1   0   0   0   0]
 [  0   0   0   4   0  18   0   0   0]]
