<a href="https://colab.research.google.com/github/ShriDurga17/Abusive-Comment-Detection/blob/main/AbusiveCommentDetection(train%2BDev).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Installing Packages

In [ ]:
!pip install scikit-multilearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.4/89.4 kB 8.6 MB/s eta 0:00:00


In [ ]:
# to convert emojis to text
!pip install emot
!pip install xgboost
!pip install Textblob

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 2.7 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import nltk.data
import numpy as np
import pandas as pd
import re
import time
import string

In [ ]:
!pip install Keras-Preprocessing
import numpy as np
import pandas as pd
import nltk
import tensorflow as tf
from nltk.corpus import stopwords
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC, SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, AdaBoostClassifier, VotingClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, f1_score, recall_score
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential, load_model
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from keras_preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical
from keras.layers import Activation, Dense, Embedding, LSTM, SpatialDropout1D, Dropout, Flatten, GRU, Conv1D, MaxPooling1D, Bidirectional
import requests
import re
!pip install ktrain
import ktrain
from ktrain import text
sns.set()
%matplotlib inline
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('gutenberg')
nltk.download('brown')
nltk.download("reuters")
nltk.download('words')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 4.6 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.3/25.3 MB 24.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 67.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 653.6/653.6 kB 44.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 19.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 57.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.8/468.8 kB 42.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ...

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package gutenberg to /root/nltk_data...
[nltk_data]   Unzipping corpora/gutenberg.zip.
[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package reuters to /root/nltk_data...
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


True

In [ ]:
import numpy as np
import pandas as pd
import re
import gc
import os
import fileinput
import string
import tensorflow as tf
import zipfile
import datetime
import sys
from tqdm  import tqdm
tqdm.pandas()
from nltk.tokenize import wordpunct_tokenize
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score, roc_auc_score


In [ ]:
from keras.preprocessing.text import Tokenizer

from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation

from sklearn.metrics import classification_report
from keras.utils import np_utils
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
from skmultilearn.ensemble import MajorityVotingClassifier
from skmultilearn.cluster import FixedLabelSpaceClusterer
from skmultilearn.problem_transform import ClassifierChain
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder


In [ ]:
from sklearn.feature_extraction.text import  CountVectorizer, TfidfTransformer,TfidfVectorizer
from sklearn.ensemble import VotingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

from textblob import TextBlob


In [ ]:
import nltk.data
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.ensemble import VotingClassifier
import pandas as pd
import re
import string
from xgboost import XGBClassifier
from sklearn.feature_extraction.text import TfidfTransformer


# Importing The Datasets

In [ ]:
df=pd.read_csv('/content/ta-misogyny-train.csv')

In [ ]:
dev=pd.read_csv('/content/ta-misogyny-dev.csv')

In [ ]:
dev[['Category','Cont']] = df.Content.str.split("\t",expand=True)

In [ ]:
dev=dev[['Category','Cont']]

In [ ]:
df[['Category','Cont']] = df.Content.str.split("\t",expand=True)

In [ ]:
df=df[['Category','Cont']]

In [ ]:
data=df

# Train Value Count

In [ ]:

df_filtered = data.mask(lambda x: x['Category'] == 'Not-Tamil')

In [ ]:
df_filtered['Category'].value_counts()

None-of-the-above    1296
Misandry              446
Counter-speech        149
Misogyny              125
Xenophobia             95
Hope-Speech            85
Homophobia             35
Transphobic             6
Name: Category, dtype: int64

In [ ]:
data_train=data

# Clean Text Import

In [ ]:
pip install clean-text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.4/175.4 kB 12.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 5.2 MB/s eta 0:00:00
  Created wheel for emoji: filename=emoji-1.7.0-py3-none-any.whl size=171033 sha256=be87220cdefe2cf41e54629d33c94ef5d92aeb00c2f79b3d0b59b10b63cf2866
  Stored in directory: /root/.cache/pip/wheels/31/8a/8c/315c9e5d7773f74b33d5ed33f075b49c6eaeb7cedbb86e2cf8
Successfully built emoji


In [ ]:
from cleantext import clean




# Data Cleaning

In [ ]:
data['clean'] = df_filtered['Cont'].apply(lambda x:clean(x))
data.head()


dev['clean'] = dev['Cont'].apply(lambda x:clean(x))
dev.head()

Category                                               Cont  \
0  None-of-the-above  எச். ராசாவால் இராமருக்கே  இழிவு. இவர் எல்லாம் ...   
1  None-of-the-above  கல்யாணம்னு  வரும்போது தான் சாதி முக்கியம் எங்க...   
2  None-of-the-above                 Tentu Kottai ஐயா நான் தமிழ் இந்து.   
3         Homophobia  Tamil selvan  அடே தேவடியாவுக்கு பிரந்தவனே பச்ச...   
4  None-of-the-above  bro நீங்க பேசறதெல்லாம் கேக்க கேக்க இரவு துக்கம...   

                               clean  
0                              . . .  
1                                     
2                     tentu kottai .  
3  tamil selvan ... . tamil selva...  
4                                bro

In [ ]:
y_train=data['Category']
y_train=df_filtered['Category']
y_test=dev['Category']


y = pd.get_dummies(df_filtered['Category']).values


y_train1=pd.get_dummies(y_train).values
y_test1=pd.get_dummies(y_test).values
diz_label = {}
for i,Category in enumerate(df_filtered.Category.factorize()[1]):
    diz_label[i] = Category

diz_label

{0: 'None-of-the-above',
 1: 'Homophobia',
 2: 'Misandry',
 3: 'Counter-speech',
 4: 'Misogyny',
 5: 'Xenophobia',
 6: 'Transphobic',
 7: 'Hope-Speech'}

# Data Pre-Processing

TF-IDF Transformer

In [ ]:


count_vect = CountVectorizer()
cv_vect= count_vect.fit(data["clean"])
cv_vect_train= count_vect.transform(data["clean"])
cv_vect_test= count_vect.transform(dev["clean"])


tfidf_transformer = TfidfTransformer()
X_tfidf = tfidf_transformer.fit(cv_vect_train)
X_tfidf_train = tfidf_transformer.transform(cv_vect_train)
X_tfidf_test = tfidf_transformer.transform(cv_vect_test)


# SMOTE Over Sampling

In [ ]:
from imblearn.over_sampling import SMOTE

sm = SMOTE(sampling_strategy='minority', random_state=42)


strategy = {0:3720, 1:3720, 2:3720, 3:3720, 4:3720, 5:3720,6:37200,7:3720}
oversample = SMOTE(sampling_strategy=strategy)
X_train, y_train = oversample.fit_resample(X_tfidf_train, y_train1)

/usr/local/lib/python3.10/dist-packages/imblearn/utils/_validation.py:313: UserWarning: After over-sampling, the number of samples (3720) in class 0 will be larger than the number of samples in the majority class (class #5 -> 1296)
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/imblearn/utils/_validation.py:313: UserWarning: After over-sampling, the number of samples (3720) in class 1 will be larger than the number of samples in the majority class (class #5 -> 1296)
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/imblearn/utils/_validation.py:313: UserWarning: After over-sampling, the number of samples (3720) in class 2 will be larger than the number of samples in the majority class (class #5 -> 1296)
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/imblearn/utils/_validation.py:313: UserWarning: After over-sampling, the number of samples (3720) in class 3 will be larger than the number of samples in the majority class (class #5 -> 1296)
  warnings.warn(
/usr

# Models

MLP Classifier

# MLP Classifier 2

In [ ]:
tfidf_vect_ngram_chars = TfidfVectorizer(analyzer='char', ngram_range=(2,3))
tfidf_vect_ngram_chars.fit(data['Cont'])
xtrain_tfidf_ngram_chars =  tfidf_vect_ngram_chars.transform(data['Cont'])
xvalid_tfidf_ngram_chars =  tfidf_vect_ngram_chars.transform(dev['Cont'])




# MLP classifier

In [ ]:
# with char n_gram
tfidf_vect_ngram_chars = TfidfVectorizer(analyzer='char', token_pattern=r'\w{1,}', ngram_range=(1,3), max_features=5000)
tfidf_vect_ngram_chars.fit(data['clean'])
xtrain_tfidf_ngram_chars =  tfidf_vect_ngram_chars.transform(data['clean'])
xvalid_tfidf_ngram_chars =  tfidf_vect_ngram_chars.transform(dev['clean'])

from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier(hidden_layer_sizes=(150,100,50), max_iter=300,activation = 'relu',solver='adam',random_state=1)
mlp.fit(xtrain_tfidf_ngram_chars,y_train1)
y_pred7=mlp.predict(xvalid_tfidf_ngram_chars)

print(classification_report(y_test1, y_pred7))
print(confusion_matrix(np.argmax(y_test1,axis=1),np.argmax(y_pred7,axis=1)))
accuracy = accuracy_score(y_test1, y_pred7)
print("Test Accuracy:", round(accuracy*100, 4))

/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:558: UserWarning: The parameter 'token_pattern' will not be used since 'analyzer' != 'word'
  warnings.warn(


              precision    recall  f1-score   support

           0       1.00      0.27      0.43        33
           1       0.88      0.78      0.82         9
           2       1.00      0.38      0.55        24
           3       0.90      0.24      0.38       116
           4       0.80      0.15      0.25        27
           5       0.71      0.98      0.82       328
           6       1.00      1.00      1.00         2
           7       1.00      0.40      0.57        20

   micro avg       0.74      0.70      0.72       559
   macro avg       0.91      0.52      0.60       559
weighted avg       0.80      0.70      0.66       559
 samples avg       0.69      0.70      0.70       559

[[ 13   0   0   0   0  20   0   0]
 [  1   7   0   0   0   1   0   0]
 [  3   0   9   0   0  12   0   0]
 [ 15   0   0  28   1  72   0   0]
 [  4   1   0   0   4  18   0   0]
 [  4   0   0   2   0 322   0   0]
 [  0   0   0   0   0   0   2   0]
 [  2   0   0   1   0  10   0   7]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.neural_network import MLPClassifier
mlp=MLPClassifier()
mlp.fit(X_tfidf_train,y_train1)
y_pred=mlp.predict(X_tfidf_test)



/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
print(classification_report(y_test1, y_pred))
print(confusion_matrix(np.argmax(y_test1,axis=1),np.argmax(y_pred,axis=1)))
accuracy = accuracy_score(y_test1, y_pred)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       1.00      0.09      0.17        33
           1       1.00      0.11      0.20         9
           2       1.00      0.04      0.08        24
           3       1.00      0.09      0.16       116
           4       0.67      0.07      0.13        27
           5       0.63      0.98      0.77       328
           6       0.00      0.00      0.00         2
           7       0.80      0.20      0.32        20

   micro avg       0.64      0.61      0.63       559
   macro avg       0.76      0.20      0.23       559
weighted avg       0.75      0.61      0.52       559
 samples avg       0.61      0.61      0.61       559

[[  3   0   0   0   0  30   0   0]
 [  3   1   0   0   0   5   0   0]
 [  0   0   1   0   0  23   0   0]
 [  7   0   0  10   1  98   0   0]
 [  6   0   0   0   2  19   0   0]
 [  5   0   0   0   0 322   0   1]
 [  1   0   0   0   0   1   0   0]
 [  1   0   0   0   0  15   0   4]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:

print("Test Accuracy:", round(accuracy*100, 4))

Test Accuracy: 61.3596


# Gaussian NB

In [ ]:
classifier = MajorityVotingClassifier(
    clusterer = FixedLabelSpaceClusterer(clusters = [[1,2,3], [0, 2, 5], [4, 5]]),
    classifier = ClassifierChain(classifier=GaussianNB())
)
classifier.fit(xtrain_tfidf_ngram_chars,y_train1)
y_pred_m=classifier.predict(xvalid_tfidf_ngram_chars)

In [ ]:
print(classification_report(y_test1, y_pred_m))
accuracy = accuracy_score(y_test1, y_pred_m)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       0.08      1.00      0.15        33
           1       0.02      1.00      0.05         9
           2       0.69      0.38      0.49        24
           3       0.53      0.23      0.32       116
           4       0.07      1.00      0.13        27
           5       1.00      0.26      0.41       328
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00        20

   micro avg       0.14      0.34      0.20       559
   macro avg       0.30      0.48      0.19       559
weighted avg       0.73      0.34      0.35       559
 samples avg       0.27      0.34      0.29       559

Test Accuracy: 22.5403


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Deep Learning

# CNN

In [ ]:
X_train=data['clean'].tolist()
X_test =dev['clean'].tolist()

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
vocabulary_size = 25000
tokenizer = Tokenizer(num_words= vocabulary_size)
tokenizer.fit_on_texts(X_train)
sequences = tokenizer.texts_to_sequences(X_train)
X_train1 = pad_sequences(sequences, maxlen=500)
sequences = tokenizer.texts_to_sequences(X_test)
X_test1 = pad_sequences(sequences, maxlen=500)




In [ ]:
from tensorflow.keras.layers import Embedding


In [ ]:
model = Sequential()
model.add(Embedding(20000, 1000, input_length=500))
model.add(Dropout(0.2))
model.add(Conv1D(64, 2, activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(100))
model.add(Dense(8, activation='softmax'))

In [ ]:
from sklearn.utils import class_weight

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.fit(X_train1, y_train1,batch_size=254,epochs=20,verbose=1,validation_split=0.1,)



Epoch 1/20
8/8 [==============================] - 44s 5s/step - loss: 1.7089 - accuracy: 0.5151 - val_loss: 1.4967 - val_accuracy: 0.5580
Epoch 2/20
8/8 [==============================] - 34s 4s/step - loss: 1.3790 - accuracy: 0.5811 - val_loss: 1.3330 - val_accuracy: 0.5580
Epoch 3/20
8/8 [==============================] - 35s 4s/step - loss: 1.3313 - accuracy: 0.5811 - val_loss: 1.3490 - val_accuracy: 0.5580
Epoch 4/20
8/8 [==============================] - 38s 5s/step - loss: 1.3250 - accuracy: 0.5811 - val_loss: 1.3095 - val_accuracy: 0.5580
Epoch 5/20
8/8 [==============================] - 34s 4s/step - loss: 1.3161 - accuracy: 0.5811 - val_loss: 1.3151 - val_accuracy: 0.5580
Epoch 6/20
8/8 [==============================] - 34s 4s/step - loss: 1.3114 - accuracy: 0.5811 - val_loss: 1.3066 - val_accuracy: 0.5580
Epoch 7/20
8/8 [==============================] - 35s 4s/step - loss: 1.3044 - accuracy: 0.5811 - val_loss: 1.3087 - val_accuracy: 0.5580
Epoch 8/20
8/8 [==================

In [ ]:
preds = model.predict(X_test1)

18/18 [==============================] - 3s 122ms/step


In [ ]:
prediction_num= np.argmax(preds,axis=1)
pred=np.argmax(preds,axis=1)
print(classification_report(np.argmax(y_test1,axis=1),np.argmax(preds,axis=1)))

              precision    recall  f1-score   support

           0       1.00      0.09      0.17        33
           1       0.50      0.11      0.18         9
           2       1.00      0.08      0.15        24
           3       0.64      0.06      0.11       116
           4       0.45      0.19      0.26        27
           5       0.62      0.99      0.76       328
           6       0.00      0.00      0.00         2
           7       0.50      0.25      0.33        20

    accuracy                           0.62       559
   macro avg       0.59      0.22      0.25       559
weighted avg       0.65      0.62      0.52       559



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
pred=np.argmax(preds,axis=1)
print(confusion_matrix(np.argmax(y_test1,axis=1),np.argmax(preds,axis=1)))

[[  3   0   0   0   0  30   0   0]
 [  0   1   0   0   3   5   0   0]
 [  0   0   2   1   0  21   0   0]
 [  0   0   0   7   2 104   0   3]
 [  0   0   0   0   5  20   0   2]
 [  0   0   0   3   1 324   0   0]
 [  0   1   0   0   0   1   0   0]
 [  0   0   0   0   0  15   0   5]]



#Machine Learning


# Decision Tree

In [ ]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(xtrain_tfidf_ngram_chars,y_train1)
y_pred_dt=model.predict(xvalid_tfidf_ngram_chars)

In [ ]:
y_pred_9 =np.argmax(y_pred_dt,axis=1)

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

label = le.fit(data['Category'])
label_t=le.fit_transform(data['Category'])
prediction9=le.inverse_transform(y_pred_9)

In [ ]:
print(classification_report(y_test1,y_pred_dt))
print(confusion_matrix(y_test1.argmax(axis=1),y_pred_dt.argmax(axis=1)))
accuracy = accuracy_score(y_test1, y_pred_dt)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       1.00      0.33      0.50        33
           1       0.88      0.78      0.82         9
           2       1.00      0.46      0.63        24
           3       0.98      0.37      0.54       116
           4       0.83      0.19      0.30        27
           5       0.73      0.94      0.82       328
           6       1.00      1.00      1.00         2
           7       1.00      0.40      0.57        20

   micro avg       0.77      0.71      0.74       559
   macro avg       0.93      0.56      0.65       559
weighted avg       0.83      0.71      0.70       559
 samples avg       0.71      0.71      0.71       559

[[ 14   0   0   0   0  19   0   0]
 [  1   7   0   0   0   1   0   0]
 [  5   0  11   0   0   8   0   0]
 [  9   0   0  43   1  63   0   0]
 [  7   1   0   0   5  14   0   0]
 [ 19   0   0   1   0 308   0   0]
 [  0   0   0   0   0   0   2   0]
 [  4   0   0   0   0   8   0   8]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(xtrain_tfidf_ngram_chars,y_train1, test_size=0.2, random_state=42)

# Random Forest

In [ ]:
from sklearn import ensemble
model = ensemble.RandomForestClassifier()
model.fit(xtrain_tfidf_ngram_chars,y_train1)
y_pred10=model.predict(xvalid_tfidf_ngram_chars)



print(classification_report(y_test1,y_pred10))
print(confusion_matrix(y_test1.argmax(axis=1),y_pred10.argmax(axis=1)))
accuracy = accuracy_score(y_test1, y_pred10)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       0.85      0.33      0.48        33
           1       0.88      0.78      0.82         9
           2       0.92      0.50      0.65        24
           3       0.94      0.38      0.54       116
           4       0.83      0.19      0.30        27
           5       0.73      0.95      0.83       328
           6       1.00      1.00      1.00         2
           7       1.00      0.40      0.57        20

   micro avg       0.77      0.72      0.74       559
   macro avg       0.89      0.57      0.65       559
weighted avg       0.81      0.72      0.70       559
 samples avg       0.72      0.72      0.72       559

[[ 13   0   0   1   0  19   0   0]
 [  1   7   0   0   0   1   0   0]
 [  4   0  12   0   0   8   0   0]
 [  7   0   1  44   1  63   0   0]
 [  6   1   0   0   5  15   0   0]
 [ 16   0   0   1   0 311   0   0]
 [  0   0   0   0   0   0   2   0]
 [  3   0   0   1   0   8   0   8]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(xtrain_tfidf_ngram_chars,y_train1)
y_pred11=knn.predict(xvalid_tfidf_ngram_chars)


print(classification_report(y_test1,y_pred11))
print(confusion_matrix(y_test1.argmax(axis=1),y_pred11.argmax(axis=1)))
accuracy = accuracy_score(y_test1, y_pred11)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       1.00      0.09      0.17        33
           1       0.75      0.33      0.46         9
           2       0.00      0.00      0.00        24
           3       0.67      0.12      0.20       116
           4       0.50      0.11      0.18        27
           5       0.67      0.94      0.78       328
           6       0.00      0.00      0.00         2
           7       1.00      0.05      0.10        20

   micro avg       0.67      0.59      0.63       559
   macro avg       0.57      0.21      0.24       559
weighted avg       0.66      0.59      0.53       559
 samples avg       0.59      0.59      0.59       559

[[ 11   0   0   1   0  21   0   0]
 [  3   3   0   0   1   2   0   0]
 [  7   0   0   0   0  17   0   0]
 [ 19   0   0  14   2  81   0   0]
 [  6   1   0   0   3  17   0   0]
 [ 17   0   0   4   0 307   0   0]
 [  1   0   0   0   0   1   0   0]
 [  5   0   0   2   0  12   0   1]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.ensemble import VotingClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier

# XGBClassifier

In [ ]:
from xgboost import XGBClassifier
xg=XGBClassifier()
xg.fit(xtrain_tfidf_ngram_chars,y_train1)
y_pred12=xg.predict(xvalid_tfidf_ngram_chars)


print(classification_report(y_test1,y_pred12))
print(confusion_matrix(y_test1.argmax(axis=1),y_pred12.argmax(axis=1)))
accuracy = accuracy_score(y_test1, y_pred12)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       1.00      0.33      0.50        33
           1       0.88      0.78      0.82         9
           2       1.00      0.38      0.55        24
           3       0.93      0.33      0.48       116
           4       0.83      0.19      0.30        27
           5       0.72      0.95      0.82       328
           6       1.00      1.00      1.00         2
           7       1.00      0.40      0.57        20

   micro avg       0.75      0.70      0.73       559
   macro avg       0.92      0.54      0.63       559
weighted avg       0.81      0.70      0.69       559
 samples avg       0.70      0.70      0.70       559

[[ 14   0   0   0   0  19   0   0]
 [  1   7   0   0   0   1   0   0]
 [  3   0   9   0   0  12   0   0]
 [ 10   0   0  38   1  67   0   0]
 [  6   1   0   0   5  15   0   0]
 [ 13   0   0   2   0 313   0   0]
 [  0   0   0   0   0   0   2   0]
 [  3   0   0   1   0   8   0   8]]
Test Accuracy:

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
import pandas as pd
import numpy as np

def clean_dataset(data):
    assert isinstance(data, pd.DataFrame), "df needs to be a pd.DataFrame"
    data.dropna(inplace=True)
    indices_to_keep = ~data.isin([np.nan, np.inf, -np.inf]).any(axis=1)
    return data[indices_to_keep].astype(np.float64)

In [ ]:
y_train=data['Category']
x_test=dev['Cont']
y_test=dev['Category']
x_train=data['Cont'].astype(str)

In [ ]:
count_vect = CountVectorizer(ngram_range=(1, 2))
transformer = TfidfTransformer(norm='l2',sublinear_tf=True)
x_train_counts = count_vect.fit_transform(x_train)
x_train_tfidf = transformer.fit_transform(x_train_counts)


x_test_counts = count_vect.transform(x_test)
x_test_tfidf = transformer.transform(x_test_counts)

print (x_train_tfidf.shape,x_test_tfidf.shape, y_train.shape, y_test.shape)

(2239, 14719) (559, 14719) (2239,) (559,)


In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
data['label'] = le.fit_transform(data['Category'])

In [ ]:
y_fit=data['label']

In [ ]:
y_fit_test=le.fit_transform(dev['Category'])

#Random Forest

In [ ]:
rfc = RandomForestClassifier(n_estimators=300, max_depth=15, random_state=42, class_weight='balanced')
rfc.fit(x_train_tfidf,y_fit)
y_pred4 = rfc.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_fit_test,y_pred4)))
print(classification_report(y_fit_test, y_pred4))
print(confusion_matrix(y_fit_test, y_pred4))


Accuracy: 0.8050089445438283
              precision    recall  f1-score   support

           0       0.65      0.91      0.76        33
           1       1.00      1.00      1.00         9
           2       0.66      0.88      0.75        24
           3       0.66      0.89      0.76       116
           4       0.81      0.93      0.86        27
           5       0.97      0.74      0.84       328
           6       1.00      1.00      1.00         2
           7       0.55      0.90      0.68        20

    accuracy                           0.81       559
   macro avg       0.79      0.90      0.83       559
weighted avg       0.85      0.81      0.81       559

[[ 30   0   0   1   0   2   0   0]
 [  0   9   0   0   0   0   0   0]
 [  0   0  21   1   0   2   0   0]
 [  4   0   1 103   3   3   0   2]
 [  0   0   0   1  25   1   0   0]
 [ 12   0  10  48   3 242   0  13]
 [  0   0   0   0   0   0   2   0]
 [  0   0   0   2   0   0   0  18]]


# Logistic Regression

In [ ]:
lr = LogisticRegression(C = 2, max_iter = 1000, n_jobs=-1)
lr.fit(x_train_tfidf, y_fit)
y_pred1 = lr.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_fit_test,y_pred1)))
print(classification_report(y_fit_test, y_pred1))
print(confusion_matrix(y_fit_test, y_pred1))

Accuracy: 0.853309481216458
              precision    recall  f1-score   support

           0       0.95      0.61      0.74        33
           1       1.00      0.67      0.80         9
           2       1.00      0.08      0.15        24
           3       0.94      0.88      0.91       116
           4       0.91      0.37      0.53        27
           5       0.81      0.99      0.89       328
           6       0.00      0.00      0.00         2
           7       1.00      0.60      0.75        20

    accuracy                           0.85       559
   macro avg       0.83      0.52      0.60       559
weighted avg       0.87      0.85      0.83       559

[[ 20   0   0   0   0  13   0   0]
 [  0   6   0   1   1   1   0   0]
 [  0   0   2   1   0  21   0   0]
 [  0   0   0 102   0  14   0   0]
 [  1   0   0   0  10  16   0   0]
 [  0   0   0   3   0 325   0   0]
 [  0   0   0   0   0   2   0   0]
 [  0   0   0   1   0   7   0  12]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# SVC

In [ ]:

svc = LinearSVC()
svc.fit(x_train_tfidf, y_fit)
y_pred_svc = svc.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_fit_test,y_pred_svc)))
print(classification_report(y_fit_test, y_pred_svc))

Accuracy: 0.9892665474060823
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       1.00      1.00      1.00         9
           2       1.00      0.96      0.98        24
           3       0.97      0.97      0.97       116
           4       1.00      1.00      1.00        27
           5       0.99      0.99      0.99       328
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00        20

    accuracy                           0.99       559
   macro avg       1.00      0.99      0.99       559
weighted avg       0.99      0.99      0.99       559



In [ ]:
print(confusion_matrix(y_fit_test, y_pred_svc))

[[ 33   0   0   0   0   0   0   0]
 [  0   9   0   0   0   0   0   0]
 [  0   0  23   1   0   0   0   0]
 [  0   0   0 113   0   3   0   0]
 [  0   0   0   0  27   0   0   0]
 [  0   0   0   2   0 326   0   0]
 [  0   0   0   0   0   0   2   0]
 [  0   0   0   0   0   0   0  20]]


# MultinomialNB

In [ ]:

mnb = MultinomialNB()
mnb.fit(x_train_tfidf, y_fit)
y_pred_mnb = mnb.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_fit_test,y_pred_mnb)))
print(classification_report(y_fit_test, y_pred_mnb))

Accuracy: 0.6386404293381037
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        33
           1       0.00      0.00      0.00         9
           2       0.00      0.00      0.00        24
           3       0.90      0.24      0.38       116
           4       1.00      0.04      0.07        27
           5       0.62      1.00      0.77       328
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00        20

    accuracy                           0.64       559
   macro avg       0.32      0.16      0.15       559
weighted avg       0.60      0.64      0.53       559



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print(confusion_matrix(y_fit_test, y_pred_mnb))

[[  0   0   0   0   0  33   0   0]
 [  0   0   0   1   0   8   0   0]
 [  0   0   0   0   0  24   0   0]
 [  0   0   0  28   0  88   0   0]
 [  0   0   0   1   1  25   0   0]
 [  0   0   0   0   0 328   0   0]
 [  0   0   0   0   0   2   0   0]
 [  0   0   0   1   0  19   0   0]]


# GradientBoostingClassifier

In [ ]:

gbc = GradientBoostingClassifier(n_estimators=100, max_features='auto', max_depth=4, random_state=1, verbose=1)
gbc.fit(x_train_tfidf, y_fit)
y_pred_gbc = gbc.predict(x_test_tfidf)
print("Accuracy: "+str(accuracy_score(y_fit_test,y_pred_gbc)))
print(classification_report(y_fit_test, y_pred_gbc))

      Iter       Train Loss   Remaining Time 
         1           1.1373            1.41m
         2           1.0714            1.61m
         3           1.0285            1.44m
         4           0.9863            1.25m
         5           0.9534            1.08m
         6           0.9216           58.01s
         7           0.8930           53.08s
         8           0.8702           49.19s
         9           0.8440           46.06s
        10           0.8238           43.62s
        20           0.6611           30.15s
        30           0.5743           24.93s
        40           0.5266           22.65s
        50           0.4904           17.60s
        60           0.4589           13.40s
        70           0.4322            9.68s
        80           0.4101            6.43s
        90           0.3891            3.24s
       100           0.3703            0.00s
Accuracy: 0.9427549194991055
              precision    recall  f1-score   support

           0   

In [ ]:
print(confusion_matrix(y_fit_test, y_pred_gbc))

[[ 33   0   0   0   0   0   0   0]
 [  0   9   0   0   0   0   0   0]
 [  0   0  23   1   0   0   0   0]
 [  0   0   0  89   0  27   0   0]
 [  0   0   0   0  27   0   0   0]
 [  0   0   0   4   0 324   0   0]
 [  0   0   0   0   0   0   2   0]
 [  0   0   0   0   0   0   0  20]]


# Ensemble Classifier

In [ ]:
mnb = MultinomialNB()
rfc= RandomForestClassifier(n_estimators=1000, max_depth=12, random_state=42)
lr = LogisticRegression(C = 2, max_iter = 1000, n_jobs=-1)
svc = SVC(probability=True)
ec=VotingClassifier(estimators=[('Multinominal NB', mnb), ('Random Forest', rfc),('Logistic Regression',lr),('Support Vector Machine',svc)], voting='soft', weights=[1,2,3,4])
ec.fit(x_train_tfidf,y_fit)
y_pred6 = ec.predict(x_test_tfidf)
print(accuracy_score(y_fit_test, y_pred6))
print(classification_report(y_fit_test, y_pred6))


0.9767441860465116
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        33
           1       1.00      1.00      1.00         9
           2       1.00      0.96      0.98        24
           3       0.96      0.92      0.94       116
           4       1.00      1.00      1.00        27
           5       0.97      0.99      0.98       328
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00        20

    accuracy                           0.98       559
   macro avg       0.99      0.98      0.99       559
weighted avg       0.98      0.98      0.98       559



In [ ]:
print(confusion_matrix(y_fit_test, y_pred6))

[[ 33   0   0   0   0   0   0   0]
 [  0   9   0   0   0   0   0   0]
 [  0   0  23   1   0   0   0   0]
 [  0   0   0 107   0   9   0   0]
 [  0   0   0   0  27   0   0   0]
 [  0   0   0   3   0 325   0   0]
 [  0   0   0   0   0   0   2   0]
 [  0   0   0   0   0   0   0  20]]


#AdaBoost

In [ ]:

abc= AdaBoostClassifier()

abc.fit(x_train_tfidf,y_fit)
y_pred_abc=abc.predict(x_test_tfidf)


print(classification_report(y_fit_test,y_pred_abc))
print(confusion_matrix(y_fit_test,y_pred_abc))
accuracy = accuracy_score(y_fit_test, y_pred_abc)
print("Test Accuracy:", round(accuracy*100, 4))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        33
           1       0.54      0.78      0.64         9
           2       0.00      0.00      0.00        24
           3       0.65      0.32      0.43       116
           4       0.00      0.00      0.00        27
           5       0.64      0.96      0.77       328
           6       1.00      0.50      0.67         2
           7       0.00      0.00      0.00        20

    accuracy                           0.64       559
   macro avg       0.35      0.32      0.31       559
weighted avg       0.52      0.64      0.55       559

[[  0   0   0   1   0  32   0   0]
 [  0   7   0   1   0   1   0   0]
 [  0   0   0   1   0  23   0   0]
 [  0   3   0  37   0  76   0   0]
 [  0   1   0   0   0  26   0   0]
 [  0   0   0  14   0 314   0   0]
 [  0   0   0   0   0   1   1   0]
 [  0   2   0   3   0  15   0   0]]
Test Accuracy: 64.2218


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Bert Model


In [ ]:

x_train=data['Cont'].astype(str)

x_test=dev['Cont']

X_train = x_train.tolist()
X_test = x_test.tolist()
y_train = y_fit.tolist()
y_test = y_fit_test.tolist()

In [ ]:
class_names = ['None-of-the-above','Homophobia','Misandry','Counter-speech','Misogyny','Xenophobia','Transphobic','Hope-Speech','Not-Tamil']

In [ ]:
(x_train,y_train), (x_val,y_val), preproc = text.texts_from_array(x_train=X_train, y_train=y_train,
                                                                       x_test=X_test, y_test=y_test,
                                                                       class_names=class_names,
                                                                       preprocess_mode='bert',
                                                                       maxlen=512,
                                                                       max_features=20000)


downloading pretrained BERT model (multi_cased_L-12_H-768_A-12.zip)...
[██████████████████████████████████████████████████]
extracting pretrained BERT model...
done.

cleanup downloaded zip...
done.

preprocessing train...
language: ta


Is Multi-Label? False
preprocessing test...
language: ta


task: text classification


In [ ]:
model = text.text_classifier('bert', train_data=(x_train,y_train), preproc=preproc)


Is Multi-Label? False
maxlen is 512


/usr/local/lib/python3.10/dist-packages/keras/initializers/initializers.py:120: UserWarning: The initializer GlorotNormal is unseeded and being called multiple times, which will return identical values each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(


done.


In [ ]:
learner = ktrain.get_learner(model, train_data=(x_train,y_train),
                             val_data=(x_val,y_val),
                             batch_size=6)


In [ ]:
learner.fit_onecycle(2e-5, 3)



begin training using onecycle policy with max lr of 2e-05...
Epoch 1/3
374/374 [==============================] - 359s 894ms/step - loss: 1.3138 - accuracy: 0.5623 - val_loss: 1.0876 - val_accuracy: 0.6708
Epoch 2/3
374/374 [==============================] - 349s 934ms/step - loss: 1.0823 - accuracy: 0.6396 - val_loss: 0.9850 - val_accuracy: 0.6905
Epoch 3/3
374/374 [==============================] - 333s 890ms/step - loss: 0.8414 - accuracy: 0.7048 - val_loss: 0.7163 - val_accuracy: 0.7925


In [ ]:
learner.validate(val_data=(x_val,y_val), class_names=class_names)


18/18 [==============================] - 28s 1s/step
                   precision    recall  f1-score   support

None-of-the-above       0.48      0.36      0.41        33
       Homophobia       1.00      0.56      0.71         9
         Misandry       0.75      0.12      0.21        24
   Counter-speech       0.80      0.90      0.85       116
         Misogyny       0.54      0.26      0.35        27
       Xenophobia       0.84      0.95      0.89       328
      Transphobic       0.00      0.00      0.00         2
      Hope-Speech       0.00      0.00      0.00        20
        Not-Tamil       0.00      0.00      0.00         0

         accuracy                           0.79       559
        macro avg       0.49      0.35      0.38       559
     weighted avg       0.76      0.79      0.76       559



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.

array([[ 12,   0,   1,   2,   1,  16,   0,   0,   1],
       [  0,   5,   0,   3,   1,   0,   0,   0,   0],
       [  1,   0,   3,   0,   0,  20,   0,   0,   0],
       [  2,   0,   0, 104,   2,   8,   0,   0,   0],
       [  4,   0,   0,   5,   7,  10,   0,   0,   1],
       [  5,   0,   0,   8,   1, 312,   0,   0,   2],
       [  0,   0,   0,   0,   1,   1,   0,   0,   0],
       [  1,   0,   0,   8,   0,   6,   0,   0,   5],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0]])